# Generated by Django 3.1.1 on 2025-05-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20250504_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_place',
            new_name='company_city',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='long_description',
        ),
        migrations.AddField(
            model_name='job',
            name='company_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
